### ISSUE TITLE
Criar página do projeto para divulgar demo

### ISSUE THREAD

**Issue by viniciustaveira** [brunoti/table-link#2]
Legal cara, bacana. Fica uma sugestão pra criar o branch "gh-pages" pra divulgar o projeto. Fiz um fork e alterei, ficaria desta forma: https://viniciustaveira.github.io/table-link

Fica bom pra facilitar a visualização do funcionamento. Você pode seguir estes passos pra configurar o gh-pages: https://help.github.com/articles/creating-project-pages-manually/

Valeu, abraço.

**Comment by brunoti** [comment]
Pode crer cara! Logo que eu tiver um tempo eu vou fazer uma page sim... 

Se puder dê uma olhada nos outros plugins que tenho feito! Qualquer contribuição desde código, sugestões como este issue, correções de ortografia como o @SirFlyann fez, são bem vindas...

Muito obrigado pela força! Abraço

**Comment by viniciustaveira** [comment]
Sim, com certeza.

Eu acho que não consigo mandar um PR pra você pois não tem o branch gh-pages no seu repositório, senão já mandava... se houver algum jeito ainda não consegui fazer :(

**Comment by brunoti** [comment]
Então, acho que não tem mesmo. Mas pode deixar... Valeu! :smile:
